# concatenar y agregar elementos

Se importa pandas y numpy, y se verifica la versión superior a 1.0

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.4.0'

Para configurar como se muestran los decimales, se utiliza la siguiente linea de codigo, tanto para pandas como para numpy

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [8]:
np.set_printoptions(precision=2)

se define un array de numeros aleatorios con numpy mediante:

- el metodo random.rand() devuelve valores aleatorios entre 0 y 1,
- el metodo random.randn() devuleve valores aleatorios de acuerto a una distribución normal.

In [9]:
x1 = np.random.rand(2,5)*10
x1

array([[1.38, 5.74, 6.61, 0.4 , 9.8 ],
       [2.27, 1.73, 8.79, 8.45, 9.52]])

In [10]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.36, -0.39, -0.69, -0.87, -0.57],
       [-0.84, -0.59, -0.16, -0.69, -0.96]])

mediante el metodo .concatenate(), se pueden unir varios arreglos de np.
- si no se define el eje, se introducen como filas adicionales,
- si se define el eje como 1, se introducen como nuevas columnas del arreglo.

In [11]:
np.concatenate([x1,x2])

array([[ 1.38,  5.74,  6.61,  0.4 ,  9.8 ],
       [ 2.27,  1.73,  8.79,  8.45,  9.52],
       [-0.36, -0.39, -0.69, -0.87, -0.57],
       [-0.84, -0.59, -0.16, -0.69, -0.96]])

In [12]:
np.concatenate([x1,x2]).shape

(4, 5)

In [13]:
np.concatenate([x1,x2], axis = 1)

array([[ 1.38,  5.74,  6.61,  0.4 ,  9.8 , -0.36, -0.39, -0.69, -0.87,
        -0.57],
       [ 2.27,  1.73,  8.79,  8.45,  9.52, -0.84, -0.59, -0.16, -0.69,
        -0.96]])

In [14]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

para el caso de las seríes se puede realizar de la misma forma.
- tanto para las series como dataframes se puede definir el indice.

In [15]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   1.38
b   5.74
c   6.61
d   0.40
e   9.80
dtype: float64

In [16]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.36
d   -0.39
e   -0.69
f   -0.87
g   -0.57
dtype: float64

In [23]:
pd.concat([s1,s2], axis=0)

a    1.38
b    5.74
c    6.61
d    0.40
e    9.80
c   -0.36
d   -0.39
e   -0.69
f   -0.87
g   -0.57
dtype: float64

en las series se puede cambiar el indice así:

In [18]:
s1.reset_index(drop=True)

0   1.38
1   5.74
2   6.61
3   0.40
4   9.80
dtype: float64

In [19]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 1.38 -0.36
1 5.74 -0.39
2 6.61 -0.69
3 0.40 -0.87
4 9.80 -0.57

como con las series, en los dataframes se puede establecer indices verticales (id) como hrizontales(columnas)
- se pueden concatenar por cualquiera de los indices.
- se pueden resetear los indices.


In [20]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 4.59 6.63
1 6.55 4.60
2 4.72 4.54

In [21]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.84 -0.82
3 -0.52 -0.52
4 -0.62 -0.25

In [26]:
pd.concat([df1,df2])

a     b
0  4.59  6.63
1  6.55  4.60
2  4.72  4.54
2 -0.84 -0.82
3 -0.52 -0.52
4 -0.62 -0.25

In [25]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 4.59 6.63   NaN   NaN
1 6.55 4.60   NaN   NaN
2 4.72 4.54 -0.84 -0.82
3  NaN  NaN -0.52 -0.52
4  NaN  NaN -0.62 -0.25

In [24]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 4.72 4.54 -0.84 -0.82

In [29]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 4.59 6.63 -0.84 -0.82
1 6.55 4.60 -0.52 -0.52
2 4.72 4.54 -0.62 -0.25

Por su parte los DataFrame tambien cuentan con el metodo __.append()__ el cual concatena solamente por filas.

In [ ]:
df1.append(df2).append(df2)

a     b
0  1.29  5.86
1  7.82  1.88
2  8.89  9.38
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

Tambien se puede realizar mediante columnas, sin embargo para esto se debe utilizar la matriz transpuesta, mediante el metodo __.T__ 

In [31]:
df1.T

0    1    2
a 4.59 6.55 4.72
b 6.63 4.60 4.54

In [33]:
df1.T.append(df2.T).T

/tmp/ipykernel_730/1041967650.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.T.append(df2.T).T


a    b     a     b
0 4.59 6.63   NaN   NaN
1 6.55 4.60   NaN   NaN
2 4.72 4.54 -0.84 -0.82
3  NaN  NaN -0.52 -0.52
4  NaN  NaN -0.62 -0.25